POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "usuario13@plataforma.com",
  "senha": "Senha123"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

###

GET http://localhost:8080/api/v1/os
Authorization: Bearer {{auth_token}}

###

GET http://localhost:8080/api/v1/os/minhas
Authorization: Bearer {{auth_token}}

###

GET http://localhost:8080/api/v1/tarefas/6
Authorization: Bearer {{auth_token}}

###

POST http://localhost:8080/api/v1/tarefas
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[
  {
    "ordemServicoId": 6,
    "statusOrdemServicoId": 1,
    "titulo": "Verificar equipamento",
    "descricao": "Realizar a inspeção inicial do equipamento informado na ordem de serviço."
  }
]

###

PATCH http://localhost:8080/api/v1/tarefas
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "id": 6,
  "titulo": "Tarefa Atualizada",
  "descricao": "Descrição Atualizada",
}

###

DELETE http://localhost:8080/api/v1/tarefas/6
Authorization: Bearer {{auth_token}}


